services:
  # Backend API Service
  - type: web
    name: mana-meeples-api
    env: node
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile && pnpm run build:render
    startCommand: cd apps/api && node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PNPM_VERSION
        value: 9.x
      - key: CORS_ORIGINS
        value: https://mana-meeples-web.onrender.com
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://tcg_admin:1FhON1ZvCR7bRry4L9UoonvorMD4BjAR@dpg-d3i3387diees738trbg0-a.singapore-postgres.render.com/tcg_singles?sslmode=require
      - key: COOKIE_DOMAIN
        value: .manaandmeeples.co.nz
      - key: ALLOWED_ORIGINS
        value: https://manaandmeeples.co.nz,https://www.manaandmeeples.co.nz,http://localhost:3000



  # Frontend Web Service
  - type: web
    name: mana-meeples-web
    env: static
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile && pnpm --filter ./apps/web run build
    staticPublishPath: ./apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://mana-meeples-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html