services:
  # Backend API Service
  - type: web
    name: mana-meeples-api
    env: node
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile && pnpm run build:render
    startCommand: cd apps/api && node dist/server.js
    
    # Custom domain for API
    domains:
      - api.manaandmeeples.co.nz
    
    envVars:
      # Node.js version
      - key: NODE_VERSION
        value: 20.x
      - key: PNPM_VERSION
        value: 9.x
      
      # Server config
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      
      # Database
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      
      # Admin Authentication - Set these in Render dashboard
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      
      # Session secret
      - key: SESSION_SECRET
        sync: false  # Set this in Render dashboard
      
      # Cookie settings for same-domain setup
      - key: COOKIE_DOMAIN
        value: .manaandmeeples.co.nz
      - key: CROSS_ORIGIN
        value: true  # Changed to true since API and frontend are on different subdomains
      
      # CORS - Allow requests from your frontend domains
      - key: ALLOWED_ORIGINS
        value: https://shop.manaandmeeples.co.nz,https://www.manaandmeeples.co.nz,https://manaandmeeples.co.nz,http://localhost:3000,http://localhost:5173
      
      # CSP Configuration
      - key: CSP_CONNECT_SRC
        value: https://api.manaandmeeples.co.nz
      
      # Email Configuration - Set these in Render dashboard if using email
      - key: OWNER_EMAIL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_FROM
        sync: false
      
      # API Keys - Set these in Render dashboard
      - key: POKEMON_TCG_API_KEY
        sync: false
      - key: TCGPLAYER_API_KEY
        sync: false

  # Frontend Web Service
  - type: web
    name: mana-meeples-web
    env: static
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile && pnpm --filter ./apps/web run build
    staticPublishPath: ./apps/web/dist
    
    # Custom domain for frontend
    domains:
      - shop.manaandmeeples.co.nz

    envVars:
      - key: VITE_API_URL
        value: https://api.manaandmeeples.co.nz
    
    routes:
      - type: rewrite
        source: /*
        destination: /index.html